name: Actualizar Noticias Diarias

# Ejecutar todos los días a las 7:15 AM (UTC+1 = 6:15 AM UTC)
on:
  schedule:
    - cron: '15 6 * * *'  # 6:15 AM UTC = 7:15 AM CET
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar scrapers
      run: |
        chmod +x run_all_scrapers.sh
        ./run_all_scrapers.sh
    
    - name: Verificar archivos actualizados
      run: |
        echo "=== Archivos JSON actualizados ==="
        ls -la scrapers_y_results/*.json
        echo "=== Contenido de index.html ==="
        head -20 index.html
    
    - name: Commit y push cambios
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No hay cambios para commitear"
        else
          git commit -m "Actualización automática de noticias - $(date '+%Y-%m-%d %H:%M')"
          git push
        fi
    
    - name: Notificar éxito
      if: success()
      run: |
        echo "✅ Noticias actualizadas exitosamente"
        echo "📅 Fecha: $(date)"
        echo "📊 Archivos actualizados:"
        ls -la scrapers_y_results/*.json | wc -l
    
    - name: Notificar error
      if: failure()
      run: |
        echo "❌ Error en la actualización de noticias"
        echo "📅 Fecha: $(date)"
        echo "🔍 Revisar logs para más detalles"
